name = "Create Fossilized"
author = "kodiitulip"
version = "1.0.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "503aa345b54da1e92da74b29750894899b9a53e19a2a858b01798224f0b91a0f"

[versions]
forge = "47.4.3"
minecraft = "1.20.1"
