name = "Create Fossilized"
author = "kodiitulip"
version = "1.0.9"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1fc7eff139e19335943c486b9a074f33048bef404bd7d7c080080f939a908b94"

[versions]
forge = "47.4.3"
minecraft = "1.20.1"
