name = "Create Fossilized"
author = "kodiitulip"
version = "1.0.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "cb0542377823feafd28ce25c2044c2c9a0f0c247fdda818d98a8c12c6f725649"

[versions]
forge = "47.4.3"
minecraft = "1.20.1"
