name = "Create Fossilized"
author = "kodiitulip"
version = "1.0.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2693cb26315a67a3535ba056409f2c58ac9da8d457f66355738a5b72610fba21"

[versions]
forge = "47.4.3"
minecraft = "1.20.1"
